### ISSUE TITLE
我无法使用2.1版本的vits2模型

### ISSUE THREAD

**Issue by ArackLiceve** [Artrajz/vits-simple-api#111]
## 运行环境

* 操作系统 (Linux/macOS/Windows)：Windows
* 部署方式 (Docker/windows快速部署包/自己搭的环境)：windows快速部署包
* Python 版本 (如果是部署包可不填)：
* 代码版本/部署包版本:  [v0.6.0](https://github.com/Artrajz/vits-simple-api/releases/tag/v0.6.0)

## 问题描述
*   使用v2.1 emo来训练了一个模型，导入后无法使用
![QQ截图20231203222325](https://github.com/Artrajz/vits-simple-api/assets/128273714/c3ad9afd-6b0a-4313-84e5-7b16b4db5071)

*   使用autodl平台进行模型训练
![QQ截图20231203222928](https://github.com/Artrajz/vits-simple-api/assets/128273714/53a3d8b0-1394-426f-b997-ce3e229c6705)

*   配置文件config.json内的 版本为"version": "2.1"
![QQ截图20231203222409](https://github.com/Artrajz/vits-simple-api/assets/128273714/8926c966-4c70-40ea-945e-e532237e4643)

*   不知道是不是软件还没适配v2.1或者是我个人原因造成的，如果是我个人原因造成的请帮帮我，我会尽可能提供更多的资料。

**Comment by Artrajz** [comment]
可以看一下日志中模型加载错误的报错吗？

**Comment by Artrajz** [comment]
日志中说缺少wav2vec2-large-robust-12-ft-emotion-msp-dim模型，你可以在这里[下载](https://openi.pcl.ac.cn/Stardust_minus/Bert-VITS2/modelmanage/model_filelist_tmpl?name=wav2vec2-large-robust-12-ft-emotion-msp-dim)
下载pytorch_model.bin后放入bert_vits2/emotional/wav2vec2-large-robust-12-ft-emotion-msp-dim文件夹中

**Comment by Ikaros-521** [comment]
借楼，首次加载v2.1的模型，报错
```
File "D:\aizb\vits-simple-api-windows-gpu-v0.6.0\bert_vits2\get_emo.py", line 83, in get_emo
    wav, sr = librosa.load(audio, 16000)
TypeError: load() takes 1 positional argument but 2 were given
```
修改后`bert_vits2\get_emo.py`正常运行
```
wav, sr = librosa.load(audio, sr=16000)
```

加载音频第一次成功，后面第二次推理时报错，加载失败
```
2023-12-07 00:19:13 [ERROR] [app.log_exception:1744] Exception on /voice/bert-vits2 [POST]
Traceback (most recent call last):
  File "D:\aizb\vits-simple-api-windows-gpu-v0.6.0\py310\lib\site-packages\flask\app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\aizb\vits-simple-api-windows-gpu-v0.6.0\py310\lib\site-packages\flask\app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\aizb\vits-simple-api-windows-gpu-v0.6.0\py310\lib\site-packages\flask\app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\aizb\vits-simple-api-windows-gpu-v0.6.0\py310\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "D:\aizb\vits-simple-api-windows-gpu-v0.6.0\tts_app\voice_api\auth.py", line 9, in check_api_key
    return func(*args, **kwargs)
  File "D:\aizb\vits-simple-api-windows-gpu-v0.6.0\tts_app\voice_api\views.py", line 480, in voice_bert_vits2_api
    audio = tts_manager.bert_vits2_infer(state)
  File "D:\aizb\vits-simple-api-windows-gpu-v0.6.0\TTSManager.py", line 375, in bert_vits2_infer
    audio = model.infer(sentence, state["id"], lang, state["sdp_ratio"], state["noise"],
  File "D:\aizb\vits-simple-api-windows-gpu-v0.6.0\bert_vits2\bert_vits2.py", line 171, in infer
    emo = self.get_emo_(reference_audio, emotion).to(self.device).unsqueeze(0)
  File "D:\aizb\vits-simple-api-windows-gpu-v0.6.0\bert_vits2\bert_vits2.py", line 161, in get_emo_
    get_emo(reference_audio, self.emotion_model, self.processor)) if reference_audio else torch.Tensor(
  File "D:\aizb\vits-simple-api-windows-gpu-v0.6.0\bert_vits2\get_emo.py", line 84, in get_emo
    wav, sr = librosa.load(audio, sr=16000)
  File "D:\aizb\vits-simple-api-windows-gpu-v0.6.0\py310\lib\site-packages\librosa\core\audio.py", line 185, in load
    raise exc
  File "D:\aizb\vits-simple-api-windows-gpu-v0.6.0\py310\lib\site-packages\librosa\core\audio.py", line 175, in load
    y, sr_native = __soundfile_load(path, offset, duration, dtype)
  File "D:\aizb\vits-simple-api-windows-gpu-v0.6.0\py310\lib\site-packages\librosa\core\audio.py", line 208, in __soundfile_load
    context = sf.SoundFile(path)
  File "D:\aizb\vits-simple-api-windows-gpu-v0.6.0\py310\lib\site-packages\soundfile.py", line 658, in __init__
    self._file = self._open(file, mode_int, closefd)
  File "D:\aizb\vits-simple-api-windows-gpu-v0.6.0\py310\lib\site-packages\soundfile.py", line 1216, in _open
    raise LibsndfileError(err, prefix="Error opening {0!r}: ".format(self.name))
soundfile.LibsndfileError: Error opening <FileStorage: '1.wav' ('audio/wav')>: Format not recognised.
2023-12-07 00:19:13 [INFO] [_internal._log:187] 127.0.0.1 - - [07/Dec/2023 00:19:13] "POST /voice/bert-vits2 HTTP/1.1" 500 -
```

**Comment by Artrajz** [comment]
> File "D:\aizb\vits-simple-api-windows-gpu-v0.6.0\bert_vits2\get_emo.py", line 83, in get_emo
    wav, sr = librosa.load(audio, 16000)
TypeError: load() takes 1 positional argument but 2 were given

应该是librosa的版本问题，requirements.txt里没有指定版本，所以部署包里自动下载了最新版本。部署包里更换版本：
```
py310\python.exe -m pip install librosa==0.9.1
```

> soundfile.LibsndfileError: Error opening <FileStorage: '1.wav' ('audio/wav')>: Format not recognised.

不清楚是什么问题，我这里不管是第几次推理，加载上传的音频时都是正常的。可能也是librosa的版本问题。
