### ISSUE TITLE
使用BertVITS2进行播放器生成时报错，无法获取音频数据

### ISSUE THREAD

**Issue by cat-undertale** [Artrajz/vits-simple-api#113]
## 运行环境

* 操作系统 (Linux/macOS/Windows)：windows
* 部署方式 (Docker/windows快速部署包/自己搭的环境)：快速部署包
* Python 版本 (如果是部署包可不填)：
* 代码版本/部署包版本:0.6.0

## 问题描述
2023-12-08 15:38:55 [INFO] [views.voice_bert_vits2_api:421] [BERT-VITS2] len:10 text：你好我是数字人小助手
2023-12-08 15:38:55 [INFO] [langid.load_model:162] initializing identifier
2023-12-08 15:38:58 [ERROR] [app.log_exception:1744] Exception on /voice/bert-vits2 [POST]
Traceback (most recent call last):
  File "E:\AIGC\VITS\vits-simple-api-windows-gpu-v0.6.0\py310\lib\site-packages\flask\app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
  File "E:\AIGC\VITS\vits-simple-api-windows-gpu-v0.6.0\py310\lib\site-packages\flask\app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "E:\AIGC\VITS\vits-simple-api-windows-gpu-v0.6.0\py310\lib\site-packages\flask\app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "E:\AIGC\VITS\vits-simple-api-windows-gpu-v0.6.0\py310\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "E:\AIGC\VITS\vits-simple-api-windows-gpu-v0.6.0\tts_app\voice_api\auth.py", line 9, in check_api_key
    return func(*args, **kwargs)
  File "E:\AIGC\VITS\vits-simple-api-windows-gpu-v0.6.0\tts_app\voice_api\views.py", line 480, in voice_bert_vits2_api
    audio = tts_manager.bert_vits2_infer(state)
  File "E:\AIGC\VITS\vits-simple-api-windows-gpu-v0.6.0\TTSManager.py", line 375, in bert_vits2_infer
    audio = model.infer(sentence, state["id"], lang, state["sdp_ratio"], state["noise"],
  File "E:\AIGC\VITS\vits-simple-api-windows-gpu-v0.6.0\bert_vits2\bert_vits2.py", line 171, in infer
    emo = self.get_emo_(reference_audio, emotion).to(self.device).unsqueeze(0)
  File "E:\AIGC\VITS\vits-simple-api-windows-gpu-v0.6.0\bert_vits2\bert_vits2.py", line 161, in get_emo_
    get_emo(reference_audio, self.emotion_model, self.processor)) if reference_audio else torch.Tensor(
TypeError: must be real number, not NoneType

## 问题复现步骤
解压部署包，把用别人的一键包训练的模型（非emo）拖入Model文件中，修改config.json后，进入界面未修改任何参数直接点击播放器生成

**Comment by cat-undertale** [comment]
是按照文档步骤已经载入了模型，但是点生成无法获取音频数据
![捕获](https://github.com/Artrajz/vits-simple-api/assets/59130571/8e47ad88-4dc8-4b6f-9786-f62830dc30b4)
![捕获2](https://github.com/Artrajz/vits-simple-api/assets/59130571/7db73f2f-bc4f-46c8-8a16-8d1e1dbefc6b)

**Comment by Artrajz** [comment]
不是v2.1的模型的话，那应该是没有在模型的配置文件`config.json`中添加版本号信息，没有版本号信息的模型都会被当成v2.1来加载。

**Comment by RayenAlex** [comment]
我也遇到了这个问题，请问解决了吗
<img width="712" alt="image" src="https://github.com/Artrajz/vits-simple-api/assets/42313761/d00be1be-bc1c-4466-8f76-f3277057b689">

**Comment by STASWIT** [comment]
## 运行环境

* 操作系统 (Linux/macOS/Windows)：windows
* 部署方式 (Docker/windows快速部署包/自己搭的环境)：快速部署包
* Python 版本 (如果是部署包可不填)：
* 代码版本/部署包版本: 0.6.0

## 问题描述
* webui内弹窗：
![image](https://github.com/Artrajz/vits-simple-api/assets/32238678/c09b2e7a-7c73-435a-9f6a-e4b68c7b6d48)
* Cmd命令行：
```
2023-12-10 16:12:54 [INFO] [_internal._log:187] Press CTRL+C to quit
2023-12-10 16:13:52 [INFO] [_internal._log:187] 127.0.0.1 - - [10/Dec/2023 16:13:52] "GET /voice/speakers HTTP/1.1" 200 -
2023-12-10 16:14:07 [INFO] [views.voice_vits_api:76] [VITS] id:0 format:wav lang:auto length:1 noise:0.33 noisew:0.4 segment_size:50
2023-12-10 16:14:07 [INFO] [views.voice_vits_api:78] [VITS] len:4 text：text
2023-12-10 16:14:07 [INFO] [views.voice_vits_api:89] [VITS] speaker id 0 does not exist
2023-12-10 16:14:07 [INFO] [_internal._log:187] 127.0.0.1 - - [10/Dec/2023 16:14:07] "GET /voice/vits?text=text HTTP/1.1" 400 -
2023-12-10 16:14:29 [INFO] [_internal._log:187] 127.0.0.1 - - [10/Dec/2023 16:14:29] "GET / HTTP/1.1" 200 -
2023-12-10 16:14:29 [INFO] [_internal._log:187] 127.0.0.1 - - [10/Dec/2023 16:14:29] "GET /static/css/plugins/bootstrap.min.css HTTP/1.1" 304 -
2023-12-10 16:14:29 [INFO] [_internal._log:187] 127.0.0.1 - - [10/Dec/2023 16:14:29] "GET /static/css/style.css HTTP/1.1" 304 -
2023-12-10 16:14:29 [INFO] [_internal._log:187] 127.0.0.1 - - [10/Dec/2023 16:14:29] "GET /static/js/index.js HTTP/1.1" 304 -
2023-12-10 16:14:29 [INFO] [_internal._log:187] 127.0.0.1 - - [10/Dec/2023 16:14:29] "GET /static/css/fileinput.min.css HTTP/1.1" 304 -
2023-12-10 16:14:29 [INFO] [_internal._log:187] 127.0.0.1 - - [10/Dec/2023 16:14:29] "GET /static/css/pages/index.css HTTP/1.1" 304 -
2023-12-10 16:14:29 [INFO] [_internal._log:187] 127.0.0.1 - - [10/Dec/2023 16:14:29] "GET /static/js/plugins/fileinput.min.js HTTP/1.1" 304 -
2023-12-10 16:14:29 [INFO] [_internal._log:187] 127.0.0.1 - - [10/Dec/2023 16:14:29] "GET /static/js/plugins/jquery-3.7.1.min.js HTTP/1.1" 304 -
2023-12-10 16:14:29 [INFO] [_internal._log:187] 127.0.0.1 - - [10/Dec/2023 16:14:29] "GET /static/js/plugins/bootstrap.bundle.min.js HTTP/1.1" 304 -
2023-12-10 16:14:29 [INFO] [_internal._log:187] 127.0.0.1 - - [10/Dec/2023 16:14:29] "GET /voice/speakers HTTP/1.1" 200 -
2023-12-10 16:14:29 [INFO] [_internal._log:187] 127.0.0.1 - - [10/Dec/2023 16:14:29] "POST /voice/default_parameter HTTP/1.1" 200 -
2023-12-10 16:14:36 [INFO] [views.voice_bert_vits2_api:418] [BERT-VITS2] id:0 format:mp3 lang:auto length:1 noise:0.33 noisew:0.4 sdp_ratio:0.2 segment_size:50 length_zh:0 length_ja:0 length_en:0
2023-12-10 16:14:36 [INFO] [views.voice_bert_vits2_api:421] [BERT-VITS2] len:2 text：你好
2023-12-10 16:14:36 [INFO] [langid.load_model:162] initializing identifier
2023-12-10 16:14:41 [ERROR] [app.log_exception:1744] Exception on /voice/bert-vits2 [POST]
Traceback (most recent call last):
  File "D:\VITS\vits-simple-api-windows-gpu-v0.6.0\py310\lib\site-packages\flask\app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\VITS\vits-simple-api-windows-gpu-v0.6.0\py310\lib\site-packages\flask\app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\VITS\vits-simple-api-windows-gpu-v0.6.0\py310\lib\site-packages\flask\app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\VITS\vits-simple-api-windows-gpu-v0.6.0\py310\lib\site-packages\flask\app.py", line 1799, in dispatch_request    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "D:\VITS\vits-simple-api-windows-gpu-v0.6.0\tts_app\voice_api\auth.py", line 9, in check_api_key
    return func(*args, **kwargs)
  File "D:\VITS\vits-simple-api-windows-gpu-v0.6.0\tts_app\voice_api\views.py", line 480, in voice_bert_vits2_api
    audio = tts_manager.bert_vits2_infer(state)
  File "D:\VITS\vits-simple-api-windows-gpu-v0.6.0\TTSManager.py", line 375, in bert_vits2_infer
    audio = model.infer(sentence, state["id"], lang, state["sdp_ratio"], state["noise"],
  File "D:\VITS\vits-simple-api-windows-gpu-v0.6.0\bert_vits2\bert_vits2.py", line 171, in infer
    emo = self.get_emo_(reference_audio, emotion).to(self.device).unsqueeze(0)
  File "D:\VITS\vits-simple-api-windows-gpu-v0.6.0\bert_vits2\bert_vits2.py", line 161, in get_emo_
    get_emo(reference_audio, self.emotion_model, self.processor)) if reference_audio else torch.Tensor(
TypeError: must be real number, not NoneType
2023-12-10 16:14:41 [INFO] [_internal._log:187] 127.0.0.1 - - [10/Dec/2023 16:14:41] "POST /voice/bert-vits2 HTTP/1.1" 500 -
```

## 问题复现步骤
模型来源于Bert-VITS2t自己训练,config.json内有版本号,这是一个三语模型  

![image](https://github.com/Artrajz/vits-simple-api/assets/32238678/8a62b72a-e685-469e-8f25-0c05d7d76c95)

根据文档启动了后台管理页面并且加载模型   

![image](https://github.com/Artrajz/vits-simple-api/assets/32238678/c6eab95b-ffd5-4795-afea-19d1fa5e3a3e)

根据其他issues #111 ,我已经重新安装了librosa==0.9.1用来解决**TypeError: load() takes 1 positional argument but 2 were given**
以及在
**vits-simple-api-windows-gpu-v0.6.0\bert_vits2\emotional\wav2vec2-large-robust-12-ft-emotion-msp-dim** 内放入了pytorch_model.bin
直到我遇到上述报错,搜索问题后没有找到解决方案,请问您能帮助我解决吗?万分感谢.

**Comment by Artrajz** [comment]
> File "D:\VITS\vits-simple-api-windows-gpu-v0.6.0\bert_vits2\bert_vits2.py", line 161, in get_emo_
    get_emo(reference_audio, self.emotion_model, self.processor)) if reference_audio else torch.Tensor(
TypeError: must be real number, not NoneType

报错中显示没有传入emotion或reference_audio，也就是说在web推理的时候要填写emotion或reference_audio。

这里确实有点不方便了，当时写的时候忘记给个默认值了。

**Comment by RayenAlex** [comment]
> ## 运行环境
> * 操作系统 (Linux/macOS/Windows)：windows
> * 部署方式 (Docker/windows快速部署包/自己搭的环境)：快速部署包
> * Python 版本 (如果是部署包可不填)：
> * 代码版本/部署包版本: 0.6.0
> 
> ## 问题描述
> * webui内弹窗：
>   ![image](https://private-user-images.githubusercontent.com/32238678/289346936-c09b2e7a-7c73-435a-9f6a-e4b68c7b6d48.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIxOTkwODgsIm5iZiI6MTcwMjE5ODc4OCwicGF0aCI6Ii8zMjIzODY3OC8yODkzNDY5MzYtYzA5YjJlN2EtN2M3My00MzVhLTlmNmEtZTRiNjhjN2I2ZDQ4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjEwVDA4NTk0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM5NjIwMmRiNGIwYTBjNTExNDVmNDRhNTQ3Y2NjNjQzMGQ2ZGFkMzA2MjkxOTFhYTY1Zjk4MWZkZWQwYjMxZDImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.9VyzEDJ8_L00_p9CKQrudnWg6IZpRVrb6lZFVPg6_K4)
> * Cmd命令行：
> 
> ```
> 2023-12-10 16:12:54 [INFO] [_internal._log:187] Press CTRL+C to quit
> 2023-12-10 16:13:52 [INFO] [_internal._log:187] 127.0.0.1 - - [10/Dec/2023 16:13:52] "GET /voice/speakers HTTP/1.1" 200 -
> 2023-12-10 16:14:07 [INFO] [views.voice_vits_api:76] [VITS] id:0 format:wav lang:auto length:1 noise:0.33 noisew:0.4 segment_size:50
> 2023-12-10 16:14:07 [INFO] [views.voice_vits_api:78] [VITS] len:4 text：text
> 2023-12-10 16:14:07 [INFO] [views.voice_vits_api:89] [VITS] speaker id 0 does not exist
> 2023-12-10 16:14:07 [INFO] [_internal._log:187] 127.0.0.1 - - [10/Dec/2023 16:14:07] "GET /voice/vits?text=text HTTP/1.1" 400 -
> 2023-12-10 16:14:29 [INFO] [_internal._log:187] 127.0.0.1 - - [10/Dec/2023 16:14:29] "GET / HTTP/1.1" 200 -
> 2023-12-10 16:14:29 [INFO] [_internal._log:187] 127.0.0.1 - - [10/Dec/2023 16:14:29] "GET /static/css/plugins/bootstrap.min.css HTTP/1.1" 304 -
> 2023-12-10 16:14:29 [INFO] [_internal._log:187] 127.0.0.1 - - [10/Dec/2023 16:14:29] "GET /static/css/style.css HTTP/1.1" 304 -
> 2023-12-10 16:14:29 [INFO] [_internal._log:187] 127.0.0.1 - - [10/Dec/2023 16:14:29] "GET /static/js/index.js HTTP/1.1" 304 -
> 2023-12-10 16:14:29 [INFO] [_internal._log:187] 127.0.0.1 - - [10/Dec/2023 16:14:29] "GET /static/css/fileinput.min.css HTTP/1.1" 304 -
> 2023-12-10 16:14:29 [INFO] [_internal._log:187] 127.0.0.1 - - [10/Dec/2023 16:14:29] "GET /static/css/pages/index.css HTTP/1.1" 304 -
> 2023-12-10 16:14:29 [INFO] [_internal._log:187] 127.0.0.1 - - [10/Dec/2023 16:14:29] "GET /static/js/plugins/fileinput.min.js HTTP/1.1" 304 -
> 2023-12-10 16:14:29 [INFO] [_internal._log:187] 127.0.0.1 - - [10/Dec/2023 16:14:29] "GET /static/js/plugins/jquery-3.7.1.min.js HTTP/1.1" 304 -
> 2023-12-10 16:14:29 [INFO] [_internal._log:187] 127.0.0.1 - - [10/Dec/2023 16:14:29] "GET /static/js/plugins/bootstrap.bundle.min.js HTTP/1.1" 304 -
> 2023-12-10 16:14:29 [INFO] [_internal._log:187] 127.0.0.1 - - [10/Dec/2023 16:14:29] "GET /voice/speakers HTTP/1.1" 200 -
> 2023-12-10 16:14:29 [INFO] [_internal._log:187] 127.0.0.1 - - [10/Dec/2023 16:14:29] "POST /voice/default_parameter HTTP/1.1" 200 -
> 2023-12-10 16:14:36 [INFO] [views.voice_bert_vits2_api:418] [BERT-VITS2] id:0 format:mp3 lang:auto length:1 noise:0.33 noisew:0.4 sdp_ratio:0.2 segment_size:50 length_zh:0 length_ja:0 length_en:0
> 2023-12-10 16:14:36 [INFO] [views.voice_bert_vits2_api:421] [BERT-VITS2] len:2 text：你好
> 2023-12-10 16:14:36 [INFO] [langid.load_model:162] initializing identifier
> 2023-12-10 16:14:41 [ERROR] [app.log_exception:1744] Exception on /voice/bert-vits2 [POST]
> Traceback (most recent call last):
>   File "D:\VITS\vits-simple-api-windows-gpu-v0.6.0\py310\lib\site-packages\flask\app.py", line 2528, in wsgi_app
>     response = self.full_dispatch_request()
>   File "D:\VITS\vits-simple-api-windows-gpu-v0.6.0\py310\lib\site-packages\flask\app.py", line 1825, in full_dispatch_request
>     rv = self.handle_user_exception(e)
>   File "D:\VITS\vits-simple-api-windows-gpu-v0.6.0\py310\lib\site-packages\flask\app.py", line 1823, in full_dispatch_request
>     rv = self.dispatch_request()
>   File "D:\VITS\vits-simple-api-windows-gpu-v0.6.0\py310\lib\site-packages\flask\app.py", line 1799, in dispatch_request    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
>   File "D:\VITS\vits-simple-api-windows-gpu-v0.6.0\tts_app\voice_api\auth.py", line 9, in check_api_key
>     return func(*args, **kwargs)
>   File "D:\VITS\vits-simple-api-windows-gpu-v0.6.0\tts_app\voice_api\views.py", line 480, in voice_bert_vits2_api
>     audio = tts_manager.bert_vits2_infer(state)
>   File "D:\VITS\vits-simple-api-windows-gpu-v0.6.0\TTSManager.py", line 375, in bert_vits2_infer
>     audio = model.infer(sentence, state["id"], lang, state["sdp_ratio"], state["noise"],
>   File "D:\VITS\vits-simple-api-windows-gpu-v0.6.0\bert_vits2\bert_vits2.py", line 171, in infer
>     emo = self.get_emo_(reference_audio, emotion).to(self.device).unsqueeze(0)
>   File "D:\VITS\vits-simple-api-windows-gpu-v0.6.0\bert_vits2\bert_vits2.py", line 161, in get_emo_
>     get_emo(reference_audio, self.emotion_model, self.processor)) if reference_audio else torch.Tensor(
> TypeError: must be real number, not NoneType
> 2023-12-10 16:14:41 [INFO] [_internal._log:187] 127.0.0.1 - - [10/Dec/2023 16:14:41] "POST /voice/bert-vits2 HTTP/1.1" 500 -
> ```
> 
> ## 问题复现步骤
> 模型来源于Bert-VITS2t自己训练,config.json内有版本号,这是一个三语模型
> 
> ![image](https://private-user-images.githubusercontent.com/32238678/289346981-8a62b72a-e685-469e-8f25-0c05d7d76c95.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIxOTkwODgsIm5iZiI6MTcwMjE5ODc4OCwicGF0aCI6Ii8zMjIzODY3OC8yODkzNDY5ODEtOGE2MmI3MmEtZTY4NS00NjllLThmMjUtMGMwNWQ3ZDc2Yzk1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjEwVDA4NTk0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZjZTc1ZTE0OWZhZjE3MDg5ZmNjMTg2MmY5YWYxYzY3ZWQ0ODZlMmMyZTZlMGQxNzMxZTMwMTEwZDVhNTEwYzYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ZX2Jsus5EYEi86dt9lcBmwWcYMWzLTKHma0WpYC_h2w)
> 
> 根据文档启动了后台管理页面并且加载模型
> 
> ![image](https://private-user-images.githubusercontent.com/32238678/289346989-c6eab95b-ffd5-4795-afea-19d1fa5e3a3e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIxOTkwODgsIm5iZiI6MTcwMjE5ODc4OCwicGF0aCI6Ii8zMjIzODY3OC8yODkzNDY5ODktYzZlYWI5NWItZmZkNS00Nzk1LWFmZWEtMTlkMWZhNWUzYTNlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjEwVDA4NTk0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg2MWZkNGI3ODcyMTk2ZmQyY2M2YTliNmRlMzliZTg2OGZjNWYwMjEyMDk2OGZmNTlmNjRlZTM4NzMwNzNhMzYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.oU_BtjROM5Ge3hmoLMVoTVgLAWf8GBtBuMKQoZONh0I)
> 
> 根据其他issues #111 ,我已经重新安装了librosa==0.9.1用来解决**TypeError: load() takes 1 positional argument but 2 were given** 以及在 **vits-simple-api-windows-gpu-v0.6.0\bert_vits2\emotional\wav2vec2-large-robust-12-ft-emotion-msp-dim** 内放入了pytorch_model.bin 直到我遇到上述报错,搜索问题后没有找到解决方案,请问您能帮助我解决吗?万分感谢.

我之前也遇到这个问题，我的解决办法是emtion 那里加个数字，比如改成emotion=1 ，就能正常返回语音了

**Comment by STASWIT** [comment]
十分感谢，问题成功解决了
