### ISSUE TITLE
部署后 app.py首次执行时报错zipfile.BadZipFile: File is not a zip file

### ISSUE THREAD

**Issue by Puratoke** [Artrajz/vits-simple-api#126]
## 运行环境

* 操作系统 (Linux/macOS/Windows)：Windows10 22H2
* 部署方式 (Docker/windows快速部署包/自己搭的环境)：Windows部署包和自己搭环境都出现了该问题
* Python 版本 (如果是部署包可不填)：3.10.11
* 代码版本/部署包版本:0.65

## 问题描述

PS C:\Users\Puratoke\Desktop\hhhao\vits-simple-api> python app.py
INFO:root:Loading yaml from C:\Users\Puratoke\Desktop\hhhao\vits-simple-api\config.yml
Building prefix dict from the default dictionary ...
DEBUG:jieba:Building prefix dict from the default dictionary ...
Loading model from cache C:\Users\Puratoke\AppData\Local\Temp\jieba.cache
DEBUG:jieba:Loading model from cache C:\Users\Puratoke\AppData\Local\Temp\jieba.cache
Loading model cost 0.590 seconds.
DEBUG:jieba:Loading model cost 0.590 seconds.
Prefix dict has been built successfully.
DEBUG:jieba:Prefix dict has been built successfully.
Traceback (most recent call last):
  File "C:\Users\Puratoke\Desktop\hhhao\vits-simple-api\app.py", line 10, in <module>
    from tts_app import frontend, voice_api, auth, admin
  File "C:\Users\Puratoke\Desktop\hhhao\vits-simple-api\tts_app\__init__.py", line 1, in <module>
    from tts_app.frontend import frontend
  File "C:\Users\Puratoke\Desktop\hhhao\vits-simple-api\tts_app\frontend\__init__.py", line 1, in <module>
    from tts_app.frontend.views import frontend
  File "C:\Users\Puratoke\Desktop\hhhao\vits-simple-api\tts_app\frontend\views.py", line 3, in <module>
    from tts_app.model_manager import model_manager
  File "C:\Users\Puratoke\Desktop\hhhao\vits-simple-api\tts_app\model_manager.py", line 1, in <module>
    from ModelManager import ModelManager
  File "C:\Users\Puratoke\Desktop\hhhao\vits-simple-api\ModelManager.py", line 14, in <module>
    from bert_vits2 import Bert_VITS2
  File "C:\Users\Puratoke\Desktop\hhhao\vits-simple-api\bert_vits2\__init__.py", line 1, in <module>
    from bert_vits2.bert_vits2 import Bert_VITS2
  File "C:\Users\Puratoke\Desktop\hhhao\vits-simple-api\bert_vits2\bert_vits2.py", line 13, in <module>
    from bert_vits2.text.cleaner import clean_text
  File "C:\Users\Puratoke\Desktop\hhhao\vits-simple-api\bert_vits2\text\cleaner.py", line 1, in <module>
    from bert_vits2.text import chinese, japanese, english, cleaned_text_to_sequence, japanese_v111, chinese_v100, \
  File "C:\Users\Puratoke\Desktop\hhhao\vits-simple-api\bert_vits2\text\english.py", line 4, in <module>
    from g2p_en import G2p
  File "C:\Users\Puratoke\AppData\Local\Programs\Python\Python310\lib\site-packages\g2p_en\__init__.py", line 1, in <module>
    from .g2p import G2p
  File "C:\Users\Puratoke\AppData\Local\Programs\Python\Python310\lib\site-packages\g2p_en\g2p.py", line 22, in <module>
    nltk.data.find('taggers/averaged_perceptron_tagger.zip')
  File "C:\Users\Puratoke\AppData\Local\Programs\Python\Python310\lib\site-packages\nltk\data.py", line 542, in find
    return ZipFilePathPointer(p, zipentry)
  File "C:\Users\Puratoke\AppData\Local\Programs\Python\Python310\lib\site-packages\nltk\compat.py", line 41, in _decorator
    return init_func(*args, **kwargs)
  File "C:\Users\Puratoke\AppData\Local\Programs\Python\Python310\lib\site-packages\nltk\data.py", line 394, in __init__
    zipfile = OpenOnDemandZipFile(os.path.abspath(zipfile))
  File "C:\Users\Puratoke\AppData\Local\Programs\Python\Python310\lib\site-packages\nltk\compat.py", line 41, in _decorator
    return init_func(*args, **kwargs)
  File "C:\Users\Puratoke\AppData\Local\Programs\Python\Python310\lib\site-packages\nltk\data.py", line 935, in __init__
    zipfile.ZipFile.__init__(self, filename)
  File "C:\Users\Puratoke\AppData\Local\Programs\Python\Python310\lib\zipfile.py", line 1269, in __init__
    self._RealGetContents()
  File "C:\Users\Puratoke\AppData\Local\Programs\Python\Python310\lib\zipfile.py", line 1336, in _RealGetContents
    raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file

## 问题复现步骤

按照文档教程进行的部署，Windows部署包在启动bat后就产生了错误，自己搭建环境时唯一区别是将pyopentalk更换为了0.3.3，其余与文档一致，产生了同样的错误
搜索zipfile.BadZipFile: File is not a zip file时并没有查询到情况相似的解决方式，因为比较小白，所以提出的问题如果太基础或者过于蠢爆了的话恳请大佬们无视就好，如果愿意给出一些小小的帮助的话万分感谢您的举手之劳
![asdsad6](https://github.com/Artrajz/vits-simple-api/assets/155087554/a4bba1e0-3891-4509-aad6-94e00659c2c8)

**Comment by Artrajz** [comment]
由于没有遇到过所以我也只能猜测下解决办法。从日志上看起来是nltk模块在下载zip时，由于某种原因没有下载完整，导致无法解压。

可以下载我打包好的[nltk_data.zip](https://github.com/Artrajz/vits-simple-api/files/13885741/nltk_data.zip)，解压到任意一个盘符的根目录，然后重新启动项目试试。

**Comment by Puratoke** [comment]
您好，非常感谢您的帮助！使用您的文件将C:\Users\用户名\AppData\Roaming\nltk_data原有文件覆盖后重新启动一切正常，在此向您表达真诚地感谢！
