### ISSUE TITLE
'NoneType' object has no attribute 'lower'大佬这个怎么解决？

### ISSUE THREAD

**Issue by dsfdfc** [Artrajz/vits-simple-api#130]
## 运行环境

* 操作系统 (Linux/macOS/Windows)：windows
* 部署方式 (Docker/windows快速部署包/自己搭的环境)：windows快速部署包
* Python 版本 (如果是部署包可不填)：
* 代码版本/部署包版本:0.6.5

## 问题描述
在config.py中改了文件路径但是Bert-VITS2还是显示未加载模型，但vits能正常使用
![{1AFB8FD2-A2F7-4db9-84DC-44C71C0D6C88}](https://github.com/Artrajz/vits-simple-api/assets/86122232/d247629f-62a0-4ae2-b6b7-2970c83074af)

## 问题复现步骤
2024-01-20 19:25:07 [INFO] [ModelManager._load_model_from_path:234] model_type:VITS model_id:0 n_speakers:4 model_path:D:\vits-simple-api-windows-cpu-v0.6.5\Model\Nene_Nanami_Rong_Tang\1374_epochs.pth
2024-01-20 19:25:07 [INFO] [ModelManager.load_model:266] Loading failed. 'NoneType' object has no attribute 'lower'
2024-01-20 19:25:07 [ERROR] [ModelManager.load_model:267] Traceback (most recent call last):
  File "D:\vits-simple-api-windows-cpu-v0.6.5\ModelManager.py", line 253, in load_model
    model_data = self._load_model_from_path(model_path, config_path)
  File "D:\vits-simple-api-windows-cpu-v0.6.5\ModelManager.py", line 175, in _load_model_from_path
    model = model_class(**model_args)
  File "D:\vits-simple-api-windows-cpu-v0.6.5\bert_vits2\bert_vits2.py", line 102, in __init__
    elif self.version.lower().replace("-", "_") in ["extra", "zh_clap"]:
AttributeError: 'NoneType' object has no attribute 'lower'

**Comment by Artrajz** [comment]
bert-vits2模型是什么版本的？检查一下config.json里是否有填写`version`。

**Comment by dsfdfc** [comment]
谢谢大佬

> bert-vits2模型是什么版本的？检查一下config.json里是否有填写。`version`
