### ISSUE TITLE
0.66cpu版本启动报错

### ISSUE THREAD

**Issue by gushuaialan1** [Artrajz/vits-simple-api#131]
## 运行环境

* 操作系统 (Linux/macOS/Windows)：windows
* 部署方式 (Docker/windows快速部署包/自己搭的环境)：windows快速部署包
* Python 版本 (如果是部署包可不填)：
* 代码版本/部署包版本:0.66 cpu

## 问题描述
提示：AttributeError: module 'torch' has no attribute 'compiler'是不是torch版本的问题？
Traceback (most recent call last):
  File "D:\AIVOICE\vits-simple-api-windows-cpu-v0.6.6\app.py", line 10, in <module>
    from tts_app.frontend.views import frontend
  File "D:\AIVOICE\vits-simple-api-windows-cpu-v0.6.6\tts_app\frontend\views.py", line 3, in <module>
    from tts_app.model_manager import model_manager
  File "D:\AIVOICE\vits-simple-api-windows-cpu-v0.6.6\tts_app\model_manager.py", line 1, in <module>
    from manager.ModelManager import ModelManager
  File "D:\AIVOICE\vits-simple-api-windows-cpu-v0.6.6\manager\ModelManager.py", line 15, in <module>
    from bert_vits2 import Bert_VITS2
  File "D:\AIVOICE\vits-simple-api-windows-cpu-v0.6.6\bert_vits2\__init__.py", line 1, in <module>
    from bert_vits2.bert_vits2 import Bert_VITS2
  File "D:\AIVOICE\vits-simple-api-windows-cpu-v0.6.6\bert_vits2\bert_vits2.py", line 10, in <module>
    from bert_vits2.models import SynthesizerTrn
  File "D:\AIVOICE\vits-simple-api-windows-cpu-v0.6.6\bert_vits2\models.py", line 12, in <module>
    from vector_quantize_pytorch import VectorQuantize
  File "D:\AIVOICE\vits-simple-api-windows-cpu-v0.6.6\py310\lib\site-packages\vector_quantize_pytorch\__init__.py", line 2, in <module>
    from vector_quantize_pytorch.residual_vq import ResidualVQ, GroupedResidualVQ
  File "D:\AIVOICE\vits-simple-api-windows-cpu-v0.6.6\py310\lib\site-packages\vector_quantize_pytorch\residual_vq.py", line 13, in <module>
    from einx import get_at
  File "D:\AIVOICE\vits-simple-api-windows-cpu-v0.6.6\py310\lib\site-packages\einx\__init__.py", line 7, in <module>
    from . import backend
  File "D:\AIVOICE\vits-simple-api-windows-cpu-v0.6.6\py310\lib\site-packages\einx\backend\__init__.py", line 27, in <module>
    _update()
  File "D:\AIVOICE\vits-simple-api-windows-cpu-v0.6.6\py310\lib\site-packages\einx\backend\__init__.py", line 25, in _update
    backends.append(backend_factories[backend_name]())
  File "D:\AIVOICE\vits-simple-api-windows-cpu-v0.6.6\py310\lib\site-packages\einx\backend\_torch.py", line 127, in make_torch_backend
    einx.lru_cache.decorate_traced_functions(torch_.compiler.allow_in_graph)
AttributeError: module 'torch' has no attribute 'compiler'

**Comment by gushuaialan1** [comment]
我看compiler is only available for PyTorch > 2.0

**Comment by Artrajz** [comment]
感谢反馈！应该是vector-quantizer-pytorch更新了，内部使用了新版本torch的函数。但由于之前测试torch 1.13.1 在显存方面表现良好，所以还是继续保持使用1.13.1版本，将vector-quantizer-pytorch替换为稍旧的版本。

**Comment by Artrajz** [comment]
已更改vector-quantizer-pytorch版本
