### ISSUE TITLE
外部绝对路径模型多了报错

### ISSUE THREAD

**Issue by zmwv823** [Artrajz/vits-simple-api#137]
## 运行环境

* 操作系统 (Linux/macOS/Windows)：
* windows10 ltsc 2021
* 部署方式 (Docker/windows快速部署包/自己搭的环境)：
* windows快速部署包CPU版本
* Python 版本 (如果是部署包可不填)：
* 代码版本/部署包版本:
0.6.6
## 问题描述
使用外部绝对路径模型，1个或2个或3个都没问题，但是我把自己收集的21个全丢进去就会报错，再减少数量就正常运行，具体到多少个会报错没去尝试，内置也没尝试：
```
2024-01-28 15:37:55 [ERROR] [logger.handle_exception:47] Uncaught exception
Traceback (most recent call last):
  File "D:\AI\vits-simple-api\app.py", line 10, in <module>
    from tts_app.frontend.views import frontend
  File "D:\AI\vits-simple-api\tts_app\frontend\views.py", line 3, in <module>
    from tts_app.model_manager import model_manager
  File "D:\AI\vits-simple-api\tts_app\model_manager.py", line 9, in <module>
    model_manager.model_init()
  File "D:\AI\vits-simple-api\manager\ModelManager.py", line 85, in model_init
    models = self.scan_path()
  File "D:\AI\vits-simple-api\manager\ModelManager.py", line 495, in scan_path
    json_file = glob.glob(dir_name + "/*.json", recursive=True)[0]
IndexError: list index out of range
```
## 问题复现步骤
多次尝试，依然能复现。
![image](https://github.com/Artrajz/vits-simple-api/assets/13308350/e73cfe8b-f964-4b9b-9ed3-6c8809040ab3)

**Comment by Artrajz** [comment]
可以看一下模型存放位置以及config.yaml中模型路径的配置吗

**Comment by zmwv823** [comment]
> 可以看一下模型存放位置以及config.yaml中模型路径的配置吗

![image](https://github.com/Artrajz/vits-simple-api/assets/13308350/cd1ac75d-84b5-4193-af26-8e35ae785330)

**Comment by Artrajz** [comment]
检查一下`models_path`下的所有文件夹，确保每个文件夹都有一个`.json`和`.pth`并且没有多余的文件夹，这个报错应该是某个文件夹找不到`.json`文件

**Comment by zmwv823** [comment]
> 检查一下`models_path`下的所有文件夹，确保每个文件夹都有一个`.json`和`.pth`并且没有多余的文件夹，这个报错应该是某个文件夹找不到`.json`文件

谢谢，确实是我这里面一个模型路径有问题。以前为了从训练界面启动推理，留了一个官方文件夹结构，模型文件在xxx/models下面。
