### ISSUE TITLE
部署包无法启动

### ISSUE THREAD

**Issue by Jacking-Chan** [Artrajz/vits-simple-api#150]
## 运行环境

* 操作系统 (Linux/macOS/Windows)：win10
* 部署方式 (Docker/windows快速部署包/自己搭的环境)：
* Python 版本 (如果是部署包可不填)：
* 代码版本/部署包版本:

## 问题描述
启动出现问题
![WS17@21ZP 5}QE6}~E8G8(K](https://github.com/Artrajz/vits-simple-api/assets/75207063/100d2254-cd83-4fc8-8f17-0b286a68093e)

**Comment by Jacking-Chan** [comment]
完整报错：
Traceback (most recent call last):
  File "D:\Program Files\vits\app.py", line 10, in <module>
    from tts_app.frontend.views import frontend
  File "D:\Program Files\vits\tts_app\frontend\views.py", line 3, in <module>
    from tts_app.model_manager import model_manager
  File "D:\Program Files\vits\tts_app\model_manager.py", line 1, in <module>
    from manager.ModelManager import ModelManager
  File "D:\Program Files\vits\manager\ModelManager.py", line 15, in <module>
    from bert_vits2 import Bert_VITS2
  File "D:\Program Files\vits\bert_vits2\__init__.py", line 1, in <module>
    from bert_vits2.bert_vits2 import Bert_VITS2
  File "D:\Program Files\vits\bert_vits2\bert_vits2.py", line 13, in <module>
    from bert_vits2.text.cleaner import clean_text
  File "D:\Program Files\vits\bert_vits2\text\cleaner.py", line 1, in <module>
    from bert_vits2.text import chinese, japanese, english, cleaned_text_to_sequence, japanese_v111, chinese_v100, \
  File "D:\Program Files\vits\bert_vits2\text\english.py", line 4, in <module>
    from g2p_en import G2p
  File "D:\Program Files\vits\py310\lib\site-packages\g2p_en\__init__.py", line 1, in <module>
    from .g2p import G2p
  File "D:\Program Files\vits\py310\lib\site-packages\g2p_en\g2p.py", line 22, in <module>
    nltk.data.find('taggers/averaged_perceptron_tagger.zip')
  File "D:\Program Files\vits\py310\lib\site-packages\nltk\data.py", line 542, in find
    return ZipFilePathPointer(p, zipentry)
  File "D:\Program Files\vits\py310\lib\site-packages\nltk\compat.py", line 41, in _decorator
    return init_func(*args, **kwargs)
  File "D:\Program Files\vits\py310\lib\site-packages\nltk\data.py", line 394, in __init__
    zipfile = OpenOnDemandZipFile(os.path.abspath(zipfile))
  File "D:\Program Files\vits\py310\lib\site-packages\nltk\compat.py", line 41, in _decorator
    return init_func(*args, **kwargs)
  File "D:\Program Files\vits\py310\lib\site-packages\nltk\data.py", line 935, in __init__
    zipfile.ZipFile.__init__(self, filename)
  File "D:\Program Files\vits\py310\lib\zipfile.py", line 1269, in __init__
    self._RealGetContents()
  File "D:\Program Files\vits\py310\lib\zipfile.py", line 1336, in _RealGetContents
    raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file

**Comment by Artrajz** [comment]
这是nltk资源未正常下载导致的，参考https://github.com/Artrajz/vits-simple-api/issues/126#issuecomment-1884493240

**Comment by Jacking-Chan** [comment]
你好，我已经收到你的邮件。

**Comment by Jacking-Chan** [comment]
收到，谢谢佬，刚发现还有closed issue，再出现问题就去这里翻一翻
