### ISSUE TITLE
gpt sovits，你好，官方推理上是有按模式切分的参数的

### ISSUE THREAD

**Issue by kingslyChen** [Artrajz/vits-simple-api#154]
## 运行环境

* 操作系统 (Linux/macOS/Windows)：
* 部署方式 (Docker/windows快速部署包/自己搭的环境)：
* Python 版本 (如果是部署包可不填)：
* 代码版本/部署包版本:

## 问题描述
gpt sovits，你好，官方推理上是有按模式切分的参数的，现在接口有这个参数么？

**Comment by Artrajz** [comment]
这里用的是按字数切分，可以设定不同的`segment_size`实现不同的切法，比如`segment_size=30`大概是一段四句话，`segment_size=17`大概是一段两句话

**Comment by Artrajz** [comment]
未配置就不会启用ngrok呀，看看报错是不是说没有下载ngrok依赖

**Comment by gushuaialan1** [comment]
> 未配置就不会启用ngrok呀，看看报错是不是说没有下载ngrok依赖

User
2024-03-20 13:12:49 [INFO] Additional phrases loaded from D:\vits-simple-api-windows-gpu-v0.6.10\data\phrases_dict.txt [in phrases_dict.load_phrases_from_file:27]
2024-03-20 13:12:49 [DEBUG] Looking up time zone info from registry [in win32._get_localzone_name:58]
2024-03-20 13:12:49 [INFO] Scheduler started [in base.start:181]
2024-03-20 13:12:49 [INFO] Added job "clean_task" to job store "default" [in base._real_add_job:895]
2024-03-20 13:12:49 [DEBUG] Using proactor: IocpProactor [in proactor_events.__init__:630]
2024-03-20 13:12:50 [ERROR] Uncaught exception [in logger.handle_exception:90]
Traceback (most recent call last):
  File "D:\vits-simple-api-windows-gpu-v0.6.10\app.py", line 77, in <module>
    listener = ngrok.forward(config.http_service.port, authtoken=config.ngrok_config.auth_token)
  File "ngrok_wrapper", line 16, in run
  File "D:\vits-simple-api-windows-gpu-v0.6.10\py310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "D:\vits-simple-api-windows-gpu-v0.6.10\py310\lib\asyncio\base_events.py", line 649, in run_until_complete
    return future.result()
  File "ngrok_wrapper", line 7, in wrap
ValueError: ('failed to connect session', 'The authtoken you specified does not look like a proper ngrok tunnel authtoken.\nYour authtoken: None\nInstructions to install your authtoken are on your ngrok dashboard:\nhttps://dashboard.ngrok.com/get-started/your-authtoken', 'ERR_NGROK_105')

没配置就会报这个错，配置了就能正常启动

**Comment by Artrajz** [comment]
发生报错时config.yaml中的ngrok是怎么配置的，我测试写null和""均不会报错

**Comment by gushuaialan1** [comment]
填的是 null  运行时就自动改成了 None
http_service:
  host: 0.0.0.0
  port: 23456
  debug: false
ngrok_config:
  auth_token: None

**Comment by gushuaialan1** [comment]
> 发生报错时config.yaml中的ngrok是怎么配置的，我测试写null和""均不会报错


填的是 null  运行时就自 动改成了 None
http_service:
  host: 0.0.0.0
  port: 23456
  debug: false
ngrok_config:
  auth_token: None

**Comment by Artrajz** [comment]
> 填的是 null 运行时就自 动改成了 None

已定位问题并修复 https://github.com/Artrajz/vits-simple-api/commit/c7790414a70cf57a23fc37ba59cd1ff1514cb7bd
