### ISSUE TITLE
报错 EOFError: Ran out of input

### ISSUE THREAD

**Issue by shinianj** [Artrajz/vits-simple-api#35]
在使用python app.py时出现了报错，日志如下：
root@ecsekei:~/vits# python3 app.py
torch:2.0.0+cu117 GPU_available:False
device:cpu device.type:cpu
Traceback (most recent call last):
  File "/root/vits/app.py", line 25, in <module>
    voice_obj, voice_speakers = merge_model(app.config["MODEL_LIST"])
  File "/root/vits/utils/merge.py", line 53, in merge_model
    obj = vits(model=i[0], config=i[1])
  File "/root/vits/voice.py", line 54, in __init__
    self.load_model(model, model_)
  File "/root/vits/voice.py", line 57, in load_model
    utils.load_checkpoint(model, self.net_g_ms)
  File "/root/vits/utils/utils.py", line 43, in load_checkpoint
    checkpoint_dict = load(checkpoint_path, map_location='cpu')
  File "/usr/local/lib/python3.10/dist-packages/torch/serialization.py", line 815, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/usr/local/lib/python3.10/dist-packages/torch/serialization.py", line 1033, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
EOFError: Ran out of input

**Comment by Artrajz** [comment]
贴一下配置文件，检查模型路径是否正确填写，这里报错说加载模型为空

**Comment by shinianj** [comment]
![}OXVB@XQ)`2 LE@%ER`4) 5](https://user-images.githubusercontent.com/105840558/236660213-eeb3d80f-45aa-42a1-bc8c-532d305d3269.png)
![07M@Q9 D 3AH_0QLRLXCKZG](https://user-images.githubusercontent.com/105840558/236660215-ec61d351-7571-4d17-a2c7-ba67a0392e6d.png)

**Comment by Artrajz** [comment]
你的模型大小是0kb![AMF36GEYZ58V@ 7_G_A%79P](https://user-images.githubusercontent.com/73542220/236660281-8f30ef1b-421d-4580-9db1-30daffd3620e.jpg)

**Comment by shinianj** [comment]
啊……很抱歉，使用了其他模型之后运行正常，打扰了，谢谢
