### ISSUE TITLE
speaker id 0 does not exist

### ISSUE THREAD

**Issue by onexuan** [Artrajz/vits-simple-api#39]
http://127.0.0.1:23456/voice/speakers 返回 {"HUBERT-VITS":[],"VITS":[],"W2V2-VITS":[]} 是不是表示失败？

http://127.0.0.1:23456/voice?text=我喜欢看中国记录片
{"message":"id 0 does not exist","status":"error"}

**Comment by Artrajz** [comment]
是的，没有加载到模型

**Comment by onexuan** [comment]
刚才改了config.py了成功了，但在我的MAC M2出现如下错误

Traceback (most recent call last):
  File "/Users/XXX/opt/anaconda3/lib/python3.9/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/XXX/opt/anaconda3/lib/python3.9/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/XXX/opt/anaconda3/lib/python3.9/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/XXX/opt/anaconda3/lib/python3.9/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/XXX/opt/anaconda3/lib/python3.9/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/XXX/opt/anaconda3/lib/python3.9/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/XXX/Dev/vits/vits-simple-api/app.py", line 38, in check_api_key
    return func(*args, **kwargs)
  File "/Users/XXX/Dev/vits/vits-simple-api/app.py", line 113, in voice_vits_api
    output = tts.vits_infer({"text": text,
  File "/Users/XXX/Dev/vits/vits-simple-api/voice.py", line 435, in vits_infer
    audio = voice_obj.get_audio(voice, auto_break=True)
  File "/Users/XXX/Dev/vits/vits-simple-api/voice.py", line 205, in get_audio
    self.get_infer_param(text=sentence, speaker_id=speaker_id, length=length, noise=noise,
  File "/Users/XXX/Dev/vits/vits-simple-api/voice.py", line 131, in get_infer_param
    stn_tst = self.get_cleaned_text(text, self.hps_ms, cleaned=cleaned)
  File "/Users/XXX/Dev/vits/vits-simple-api/voice.py", line 71, in get_cleaned_text
    text_norm = text_to_sequence(text, hps.symbols, hps.data.text_cleaners)
  File "/Users/XXX/Dev/vits/vits-simple-api/text/__init__.py", line 17, in text_to_sequence
    clean_text = _clean_text(text, cleaner_names)
  File "/Users/XXX/Dev/vits/vits-simple-api/text/__init__.py", line 31, in _clean_text
    text = cleaner(text)
  File "/Users/XXX/Dev/vits/vits-simple-api/text/cleaners.py", line 115, in zh_ja_mixture_cleaners
    from text.japanese import japanese_to_romaji_with_accent
  File "/Users/XXX/Dev/vits/vits-simple-api/text/japanese.py", line 3, in <module>
    import pyopenjtalk
  File "/Users/XXX/opt/anaconda3/lib/python3.9/site-packages/pyopenjtalk/__init__.py", line 20, in <module>
    from pyopenjtalk.htsengine import HTSEngine
ImportError: dlopen(/Users/XXX/opt/anaconda3/lib/python3.9/site-packages/pyopenjtalk/htsengine.cpython-39-darwin.so, 0x0002): Library not loaded: /usr/local/opt/libomp/lib/libomp.dylib
  Referenced from: <7B44E2ED-956F-3CEA-903A-C5BB143C92EB> /Users/XXX/opt/anaconda3/lib/python3.9/site-packages/pyopenjtalk/htsengine.cpython-39-darwin.so
  Reason: tried: '/usr/local/opt/libomp/lib/libomp.dylib' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64')), '/System/Volumes/Preboot/Cryptexes/OS/usr/local/opt/libomp/lib/libomp.dylib' (no such file), '/usr/local/opt/libomp/lib/libomp.dylib' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64')), '/usr/local/lib/libomp.dylib' (no such file), '/usr/lib/libomp.dylib' (no such file, not in dyld cache), '/opt/homebrew/Cellar/libomp/14.0.6/lib/libomp.dylib' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64')), '/System/Volumes/Preboot/Cryptexes/OS/opt/homebrew/Cellar/libomp/14.0.6/lib/libomp.dylib' (no such file), '/opt/homebrew/Cellar/libomp/14.0.6/lib/libomp.dylib' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64')), '/usr/local/lib/libomp.dylib' (no such file), '/usr/lib/libomp.dylib' (no such file, not in dyld cache)

**Comment by Artrajz** [comment]
mac上使用openjtalk遇到的问题，由于我没有用过mac所以也不知道如何解决。

如果你不需要使用日语的话，可以选择注释掉使用openjtalk的部分。在text/cleaners.py中注释掉
```
def zh_ja_mixture_cleaners(text):
    from text.mandarin import chinese_to_romaji
    # from text.japanese import japanese_to_romaji_with_accent
    text = re.sub(r'\[ZH\](.*?)\[ZH\]',
                  lambda x: chinese_to_romaji(x.group(1)) + ' ', text)
    # text = re.sub(r'\[JA\](.*?)\[JA\]', lambda x: japanese_to_romaji_with_accent(
    #     x.group(1)).replace('ts', 'ʦ').replace('u', 'ɯ').replace('...', '…') + ' ', text)
    text = re.sub(r'\s+$', '', text)
    text = re.sub(r'([^\.,!\?\-…~])$', r'\1.', text)
    return text
```
其他cleaner用类似的方法注释

如果确实要使用日语的话，只能自己找找解决方案了😢

**Comment by onexuan** [comment]
没有去掉，是我ln libomp 到/usr/local/opt/libomp/lib/ 目录后没权限导致，M2跑起来了
