### ISSUE TITLE
是我的问题吗？看log

### ISSUE THREAD

**Issue by 40740** [Artrajz/vits-simple-api#49]
DEBUG:vits-simple-api:[GD]君不见，黄河之水天上来，奔流到海不复回。君不见，高堂明镜悲白发，朝如青丝暮成雪[GD]
ERROR:app:Exception on /voice/w2v2-vits [POST]
Traceback (most recent call last):
  File "C:\Users\lin85\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\lin85\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\lin85\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\lin85\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "G:\AI\vits接口\VITS\app.py", line 44, in check_api_key
    return func(*args, **kwargs)
  File "G:\AI\vits接口\VITS\app.py", line 239, in voice_w2v2_api
    output = tts.w2v2_vits_infer({"text": text,
  File "G:\AI\vits接口\VITS\voice.py", line 454, in w2v2_vits_infer
    audio = voice_obj.get_audio(voice, auto_break=True)
  File "G:\AI\vits接口\VITS\voice.py", line 216, in get_audio
    self.get_infer_param(text=sentence, speaker_id=speaker_id, length=length, noise=noise,
  File "G:\AI\vits接口\VITS\voice.py", line 119, in get_infer_param
    stn_tst = self.get_cleaned_text(text, self.hps_ms, cleaned=cleaned)
  File "G:\AI\vits接口\VITS\voice.py", line 59, in get_cleaned_text
    text_norm = text_to_sequence(text, hps.symbols, hps.data.text_cleaners)
  File "G:\AI\vits接口\VITS\text\__init__.py", line 17, in text_to_sequence
    clean_text = _clean_text(text, cleaner_names)
  File "G:\AI\vits接口\VITS\text\__init__.py", line 31, in _clean_text
    text = cleaner(text)
  File "G:\AI\vits接口\VITS\text\cleaners.py", line 241, in chinese_dialect_cleaners
    text = re.sub(r'\[GD\](.*?)\[GD\]',
  File "C:\Users\lin85\AppData\Local\Programs\Python\Python310\lib\re.py", line 209, in sub
    return _compile(pattern, flags).sub(repl, string, count)
  File "G:\AI\vits接口\VITS\text\cleaners.py", line 242, in <lambda>
    lambda x: cantonese_to_ipa(x.group(1)) + ' ', text)
  File "G:\AI\vits接口\VITS\text\cantonese.py", line 62, in cantonese_to_ipa
    text = converter.convert(text).replace('-', '').replace('$', ' ')
  File "C:\Users\lin85\AppData\Local\Programs\Python\Python310\lib\site-packages\opencc\__init__.py", line 87, in convert
    retv_i = libopencc.opencc_convert_utf8(self._od, text, len(text))
OSError: exception: access violation reading 0xFFFFFFFFFFFFFFFF
INFO:werkzeug:127.0.0.1 - - [31/May/2023 10:51:14] "POST /voice/w2v2-vits HTTP/1.1" 500 -
DEBUG:urllib3.connectionpool:http://127.0.0.1:23456 "POST /voice/w2v2-vits HTTP/1.1" 500 265

**Comment by 40740** [comment]
同一个环境，但我在之前的版本上就没有出现这个，更新了新版后出现了。

**Comment by Artrajz** [comment]
看看是不是路径有中文的原因

**Comment by 40740** [comment]
是的! ！！ 神奇！！其他的语言，中文路径就没问题。
