### ISSUE TITLE
你好 关于请求报错 列表正常输出 但是语音无法合成 合成出的语音仅1kb 0s 无法播放

### ISSUE THREAD

**Issue by luosheng520qaq** [Artrajz/vits-simple-api#54]
报错代码如下

[E 230613 19:09:03 fastlid:170] fastlid.set_languages is not a list
[JA]こんにちは[JA]
ERROR:app:Exception on /voice [POST]
Traceback (most recent call last):
  File "E:\aila\API\vits-simple-api-windows_3\vits-simple-api\py310\lib\site-packages\flask\app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
  File "E:\aila\API\vits-simple-api-windows_3\vits-simple-api\py310\lib\site-packages\flask\app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "E:\aila\API\vits-simple-api-windows_3\vits-simple-api\py310\lib\site-packages\flask\app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "E:\aila\API\vits-simple-api-windows_3\vits-simple-api\py310\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "E:\aila\API\vits-simple-api-windows_3\vits-simple-api\app.py", line 37, in check_api_key
    return func(*args, **kwargs)
  File "E:\aila\API\vits-simple-api-windows_3\vits-simple-api\app.py", line 136, in voice_api
    output = real_obj.create_infer_task(text=text,
  File "E:\aila\API\vits-simple-api-windows_3\vits-simple-api\voice.py", line 211, in create_infer_task
    self.get_infer_param(text=sentence, speaker_id=speaker_id, length=length, noise=noise,
  File "E:\aila\API\vits-simple-api-windows_3\vits-simple-api\voice.py", line 147, in get_infer_param
    stn_tst = self.get_cleaned_text(text, self.hps_ms, cleaned=cleaned)
  File "E:\aila\API\vits-simple-api-windows_3\vits-simple-api\voice.py", line 71, in get_cleaned_text
    text_norm = text_to_sequence(text, hps.symbols, hps.data.text_cleaners)
  File "E:\aila\API\vits-simple-api-windows_3\vits-simple-api\text\__init__.py", line 17, in text_to_sequence
    clean_text = _clean_text(text, cleaner_names)
  File "E:\aila\API\vits-simple-api-windows_3\vits-simple-api\text\__init__.py", line 28, in _clean_text
    cleaner = getattr(cleaners, name)
AttributeError: module 'text.cleaners' has no attribute 'custom_cleaners'
INFO:werkzeug:127.0.0.1 - - [13/Jun/2023 19:09:03] "POST /voice HTTP/1.1" 500 -

![({JC}3SG@JE~ J}3K IY(G7](https://github.com/Artrajz/vits-simple-api/assets/107746729/ef615250-30dc-4454-a732-d09da9029113)

**Comment by Artrajz** [comment]
`config.json`中的`text_cleaners`是`custom_cleaners`吗

**Comment by luosheng520qaq** [comment]
是的
![image](https://github.com/Artrajz/vits-simple-api/assets/107746729/eaf66674-2e52-4838-90d9-b14bc8983ea4)
bingq  我试过 post请求报错 get请求报错404

**Comment by Artrajz** [comment]
这是因为我的程序中没有这个`cleaner`，可以考虑自行移植过来。移植方法是在`text/cleaners.py`中添加`custom_cleaners`这一函数，而函数的内容就要从你下载模型的地方找了。

**Comment by luosheng520qaq** [comment]
您好 我已经查阅了原模型地址 能麻烦您更加详细的说明我应该移植哪些内容吗

**Comment by Artrajz** [comment]
以这个`cleaner`为例
```
def bert_chinese_cleaners(text):
    from text import mandarin
    matches = re.findall(r"\[ZH\](.*?)\[ZH\]", text)
    text = "".join(matches)
    if text[-1] not in [".", "。", ",", "，"]: text += "."
    text = mandarin.symbols_to_chinese(text)
    text = mandarin.number_transform_to_chinese(text)
    return text
```
这个cleaner中主要的代码是
```
matches = re.findall(r"\[ZH\](.*?)\[ZH\]", text) # 语言标注
text = "".join(matches)
```
和
```
text = mandarin.number_transform_to_chinese(text) # clean text
```
第一段根据模型语言修改。第二段在原模型的程序里找，第二段这个函数方法的作用是文本转音素，名字会不同，源程序里的`cleaner`结构也不一定和我相同，所以要分析一下源程序是怎么处理的。修改这两个主要功能基本就能用了，方法中其余的代码只是对文本做一些读数字日期之类的预处理。

**Comment by Artrajz** [comment]
以这个`cleaner`为例
```
def chinese_cleaners(text):
    '''Pipeline for Chinese text'''
    from text.mandarin import number_to_chinese, chinese_to_bopomofo, latin_to_bopomofo, symbols_to_chinese

    def clean(text):
        text = symbols_to_chinese(text)
        text = number_to_chinese(text)
        text = chinese_to_bopomofo(text)
        text = latin_to_bopomofo(text)
        text = re.sub(r'([ˉˊˇˋ˙])$', r'\1。', text)
        return text

    text = re.sub(r'\[ZH\](.*?)\[ZH\]', lambda x: clean(x.group(1)) + ' ', text)
    return text
```
这个cleaner中主要功能的部分是
```
text = chinese_to_bopomofo(text)
text = latin_to_bopomofo(text)
```
这个要在原模型的程序里找，这个作用是文本转音素，名字会不同，源程序里的`cleaner`结构也不一定和我相同，所以要分析一下源程序是怎么处理的。

然后将`r'\[ZH\](.*?)\[ZH\]'`修改为模型语言的标注。

修改这两个基本就能用了，方法中其余的代码只是对文本做一些读数字、日期之类的预处理。

**Comment by luosheng520qaq** [comment]
好的 感谢
