### ISSUE TITLE
推理Bert-VITS2发生报错

### ISSUE THREAD

**Issue by boool369** [Artrajz/vits-simple-api#78]
## 使用报脸部署加载[Taffy-Bert-VITS2](https://huggingface.co/spaces/XzJosh/Taffy-Bert-VITS2)这个模型发生以下报错
![image](https://github.com/Artrajz/vits-simple-api/assets/127376060/6b1596f2-2603-4e72-813b-eb90692e56be)
```
INFO:vits-simple-api:[Bert-VITS2] id:0 format:wav lang:ZH length:1.0 noise:0.33 noisew:0.4 sdp_ratio:0.2
INFO:vits-simple-api:[Bert-VITS2] len:18 text：关注永雏塔菲喵，关注永雏塔菲谢谢喵！
ERROR:app:Exception on /voice/bert-vits2 [GET]
Traceback (most recent call last):
  File "/home/user/.local/lib/python3.10/site-packages/flask/app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/user/.local/lib/python3.10/site-packages/flask/app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/user/.local/lib/python3.10/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/user/.local/lib/python3.10/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/user/app/app.py", line 35, in check_api_key
    return func(*args, **kwargs)
  File "/home/user/app/app.py", line 477, in voice_bert_vits2_api
    audio = tts.bert_vits2_infer(task, fname)
  File "/home/user/app/voice.py", line 313, in bert_vits2_infer
    audio = voice_obj.get_audio(voice, auto_break=True)
  File "/home/user/app/bert_vits2/bert_vits2.py", line 83, in get_audio
    audio = self.infer(sentence, sdp_ratio, noise_scale, noise_scale_w, length_scale, sid)
  File "/home/user/app/bert_vits2/bert_vits2.py", line 64, in infer
    audio = self.net_g.infer(x_tst, x_tst_lengths, speakers, tones, lang_ids, bert, sdp_ratio=sdp_ratio
  File "/home/user/app/bert_vits2/models.py", line 656, in infer
    g = self.emb_g(sid).unsqueeze(-1)  # [b, h, 1]
  File "/home/user/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1614, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'SynthesizerTrn' object has no attribute 'emb_g'
INFO:werkzeug:10.16.31.122 - - [20/Sep/2023 15:07:31] "GET /voice/bert-vits2?text=关注永雏塔菲喵，关注永雏塔菲谢谢喵！&id=0&t=1695215249303 HTTP/1.1" 500 -
```

**Comment by Artrajz** [comment]
这个报错原因可以看https://github.com/Artrajz/vits-simple-api/issues/72#issuecomment-1713222113
github这边的main分支已经修复这个问题，但是hugging face那边没有同步更新。现在已经将那边代码也更新了，可以重新试一下。

**Comment by boool369** [comment]
> 这个报错原因可以看[#72 （comment）](https://github.com/Artrajz/vits-simple-api/issues/72#issuecomment-1713222113) github这边的main分支已经修复这个问题，但是hugging face那边没有同步更新。现在已经将那边代码也更新了，可以重新试一下。

感谢回复，问题已解决
