### ISSUE TITLE
[推理Bert-VITS2发生报错]

### ISSUE THREAD

**Issue by SeaL773** [Artrajz/vits-simple-api#82]
报错如下：

ERROR:vits-simple-api:Uncaught exception
Traceback (most recent call last):
  File "E:\github\Vits\vits-simple-api\app.py", line 28, in <module>
    tts = merge_model(app.config["MODEL_LIST"])
  File "E:\github\Vits\vits-simple-api\utils\merge.py", line 134, in merge_model
    obj = vits(model=i[0], config=i[1], model_=hubert, model_type="hubert")
  File "E:\github\Vits\vits-simple-api\voice.py", line 48, in __init__
    self.load_model(model, model_)
  File "E:\github\Vits\vits-simple-api\voice.py", line 51, in load_model
    utils.load_checkpoint(model, self.net_g_ms)
  File "E:\github\Vits\vits-simple-api\utils\utils.py", line 59, in load_checkpoint
    model.load_state_dict(new_state_dict)
  File "E:\software\Anaconda\envs\Vits_api\lib\site-packages\torch\nn\modules\module.py", line 2041, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for SynthesizerTrn:
        size mismatch for dp.proj.weight: copying a param with shape torch.Size([1, 256, 1]) from checkpoint, the shape in current model is torch.Size([192, 192, 1]).
        size mismatch for dp.proj.bias: copying a param with shape torch.Size([1]) from checkpoint, the shape in current model is torch.Size([192]).
        
我推断是config.json与模型不匹配
但是使用相同模型以及json文件，在Bert-VITS原项目下正常运行
也许是hubert-soft-0d54a1f4.pt这个模型有误？
搜同名模型随便下了一个

**Comment by SeaL773** [comment]
重新拉了一份，已解决
git pull的时候vits-simple-api的config文件没更新
导致无法识别bert-vits模型
