### ISSUE TITLE
不知道为什么，我用2.0模型中英混读读不了，日语也不能读

### ISSUE THREAD

**Issue by ty10235270** [Artrajz/vits-simple-api#99]

**Comment by Artrajz** [comment]
可以详细说明一下操作过程，以及给出必要的信息（日志，配置文件等）

**Comment by ty10235270** [comment]
> 可以详细说明一下操作过程，以及给出必要的信息（日志，配置文件等）

2023-11-21 16:55:42 [INFO] [views.voice_bert_vits2_api:408] [BERT-VITS2] id:36 format:wav lang:ja length:1 noise:0.33 noisew:0.4 sdp_ratio:0.2 segment_size:50
2023-11-21 16:55:42 [INFO] [views.voice_bert_vits2_api:410] [BERT-VITS2] len:18 text：昨日までの私は、もうどこにもいない。
2023-11-21 16:55:42 [ERROR] [app.log_exception:1744] Exception on /voice/bert-vits2 [POST]
Traceback (most recent call last):
  File "E:\aaaa\vits-simple-api-windows-gpu-v0.6.0-alpha.10\py310\lib\site-packages\flask\app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
  File "E:\aaaa\vits-simple-api-windows-gpu-v0.6.0-alpha.10\py310\lib\site-packages\flask\app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "E:\aaaa\vits-simple-api-windows-gpu-v0.6.0-alpha.10\py310\lib\site-packages\flask\app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "E:\aaaa\vits-simple-api-windows-gpu-v0.6.0-alpha.10\py310\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "E:\aaaa\vits-simple-api-windows-gpu-v0.6.0-alpha.10\tts_app\voice_api\auth.py", line 9, in check_api_key
    return func(*args, **kwargs)
  File "E:\aaaa\vits-simple-api-windows-gpu-v0.6.0-alpha.10\tts_app\voice_api\views.py", line 460, in voice_bert_vits2_api
    audio = tts_manager.bert_vits2_infer(state)
  File "E:\aaaa\vits-simple-api-windows-gpu-v0.6.0-alpha.10\TTSManager.py", line 366, in bert_vits2_infer
    audio = model.infer(sentence, state["id"], lang, state["sdp_ratio"], state["noise"],
  File "E:\aaaa\vits-simple-api-windows-gpu-v0.6.0-alpha.10\bert_vits2\bert_vits2.py", line 155, in infer
    audio = self.net_g.infer(x_tst, x_tst_lengths, speakers, tones, lang_ids, zh_bert, ja_bert, en_bert,
  File "E:\aaaa\vits-simple-api-windows-gpu-v0.6.0-alpha.10\bert_vits2\models.py", line 694, in infer
    o = self.dec((z * y_mask)[:, :, :max_len], g=g)
  File "E:\aaaa\vits-simple-api-windows-gpu-v0.6.0-alpha.10\py310\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "E:\aaaa\vits-simple-api-windows-gpu-v0.6.0-alpha.10\bert_vits2\models.py", line 415, in forward
    xs = self.resblocks[i * self.num_kernels + j](x)
  File "E:\aaaa\vits-simple-api-windows-gpu-v0.6.0-alpha.10\py310\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "E:\aaaa\vits-simple-api-windows-gpu-v0.6.0-alpha.10\bert_vits2\modules.py", line 213, in forward
    xt = F.leaky_relu(x, LRELU_SLOPE)
  File "E:\aaaa\vits-simple-api-windows-gpu-v0.6.0-alpha.10\py310\lib\site-packages\torch\nn\functional.py", line 1632, in leaky_relu
    result = torch._C._nn.leaky_relu(input, negative_slope)
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 20.00 MiB (GPU 0; 6.00 GiB total capacity; 5.40 GiB already allocated; 0 bytes free; 5.43 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
2023-11-21 16:55:42 [INFO] [_internal._log:187] 192.168.21.5 - - [21/Nov/2023 16:55:42] "POST /voice/bert-vits2 HTTP/1.1" 500 -

**Comment by ty10235270** [comment]
> 可以详细说明一下操作过程，以及给出必要的信息（日志，配置文件等）

2.0模型日语一开始下了个压缩包，我看了下是18年的，然后就一直无法获取音频，上面是命令窗口的报错显示

**Comment by Artrajz** [comment]
日志显示爆显存了，2.0是需要比较多显存的，因为加载的bert模型多了也比较大。可以尝试在模型的配置文件中指定语言比如说中日，就可以只加载中日的bert模型，减少点显存占用，填写方法可以看文档。

**Comment by Artrajz** [comment]
你是同时加载了2.0和1.1.1的模型吗？这两个版本的模型用了不同的日语bert模型，占用肯定是要更多的。

**Comment by ty10235270** [comment]
> 你是同时加载了2.0和1.1.1的模型吗？这两个版本的模型用了不同的日语bert模型，占用肯定是要更多的。

感谢，解决了。只加载2.0的模型没问题
